version: '3'

networks:
  myip:
    external: true

services:
  myip:
    build: .
#    ports: 
#      - 8110:1325
    networks:
      - myip
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myip.entrypoints=http"
      - "traefik.http.routers.myip.rule=Host(`myip.orkhive.de`)"
      - "traefik.http.middlewares.myip-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.myip.middlewares=myip-https-redirect"
      - "traefik.http.routers.myip-secure.entrypoints=https"
      - "traefik.http.routers.myip-secure.rule=Host(`myip.orkhive.de`)"
      - "traefik.http.routers.myip-secure.tls=true"
      - "traefik.http.routers.myip-secure.tls.certresolver=http"
      - "traefik.http.routers.myip-secure.service=myip"
      - "traefik.http.services.myip.loadbalancer.server.port=1325"
      - "traefik.docker.network=myip"
